# This is a basic workflow to help you get started with Actions

name: Get level 1

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        lon: [-1,0]
        lat: [-1,0]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Check free space
        run: |
          echo "Free space:"
          df -h
      - name: Get Level 1 map
        run: |
          sudo apt update
          sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
          sudo apt-get install -y nodejs
          npm install -g query-overpass
          export x1=$((${{matrix.lon}}*180))
          export x2=$(((${{matrix.lon}}+1)*180))
          export y1=$((${{matrix.lat}}*90))
          export y2=$(((${{matrix.lat}}+1)*90))
          #echo 'nwr($x1,$y1,$x2,$y2);out;' | query-overpass --overpass-url https://overpass.kumi.systems/api/interpreter
          echo 'nwr(0,0,1,1);out;' | query-overpass --overpass-url https://overpass.kumi.systems/api/interpreter > out.geojson
          ls -l
